export { default as HomeHero } from './hero'
export { default as HomePopularCourse } from './popular-courses'
export { default as HomeFeature } from './feature'
export { default as HomeSuccessStories } from './alumni'
export { default as HomeContact } from './contact'
